global:
  scrape_interval:     15s
  evaluation_interval: 5s
  scrape_timeout:      4s
  external_labels:
      monitor: 'codelab-monitor'

scrape_configs:
  - job_name:        'ptus'
    scrape_interval: 5s
    static_configs:
      - targets: ['ptus:9090']

  - job_name:        'lki'
    scrape_interval: 5s
    static_configs:
      - targets: ['lki:3100']

  - job_name:        'grfn'
    scrape_interval: 5s
    static_configs:
      - targets: ['grfn:3000']
